// app/report/postmanGenerator.js
import fs from "fs/promises";
import path from "path";

export async function generatePostmanCollection(
  testCases,
  outputPath = "generated/postman_collection.json"
) {
  if (!Array.isArray(testCases)) testCases = [];

  console.log(`📦 Preparing Postman collection with ${testCases.length} test cases...`);

  function inferStatus(tc) {
    // 1️⃣ Use explicit expectedStatus if valid
    if (tc && tc.expectedStatus && Number(tc.expectedStatus) > 0) {
      return Number(tc.expectedStatus);
    }

    // 2️⃣ Negative keywords
    const name = (tc?.name || "").toLowerCase();
    if (name.includes("missing") || name.includes("invalid") || name.includes("error") || name.includes("not found")) {
      return 400;
    }

    // 3️⃣ Based on HTTP method
    const method = (tc?.method || "GET").toUpperCase();
    if (method === "GET") return 200;
    if (method === "POST") return 201;
    if (method === "PUT" || method === "PATCH") return 200;
    if (method === "DELETE") return 204;

    // default
    return 200;
  }

  const collection = {
    info: {
      name: "AI Divergence Test Suite",
      _postman_id: "auto-generated-" + Date.now(),
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
      description:
        "This collection is auto-generated by the AI Divergence Predictor. Each test checks contract consistency."
    },

    item: testCases.map(tc => {
      const method = (tc.method || "GET").toUpperCase();
      const status = inferStatus(tc);

      return {
        name: tc.name || `${method} ${tc.path}`,
        request: {
          method,
          header: [{ key: "Content-Type", value: "application/json" }],
          url: {
            raw: `{{baseUrl}}${tc.path}`,
            host: ["{{baseUrl}}"],
            path: tc.path ? tc.path.replace(/^\//, "").split("/") : []
          },
          body: tc.requestBody
            ? {
                mode: "raw",
                raw: JSON.stringify(tc.requestBody, null, 2)
              }
            : undefined
        },

        event: [
          {
            listen: "test",
            script: {
              exec: [
                `pm.test("Status code should be ${status}", function () {`,
                `    pm.response.to.have.status(${status});`,
                `});`
              ]
            }
          }
        ],

        response: []
      };
    }),

    variable: [
      { key: "baseUrl", value: "http://localhost:3000" }
    ]
  };

  const dir = path.dirname(outputPath);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(outputPath, JSON.stringify(collection, null, 2));

  console.log(`✅ Postman collection generated: ${outputPath}`);
  return outputPath;
}
