// app/report/postmanGenerator.js
import fs from "fs/promises";
import path from "path";

export async function generatePostmanCollection(
  testCases,
  outputPath = "generated/postman_collection.json"
) {
  if (!Array.isArray(testCases)) testCases = [];

  console.log(`📦 Preparing Postman collection with ${testCases.length} test cases...`);

  const collection = {
    info: {
      name: "AI Divergence Test Suite",
      _postman_id: "auto-generated-" + Date.now(),
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
      description:
        "This collection is auto-generated by the AI Divergence Predictor. Each test case checks for schema mismatch or divergence between Swagger vs implementation.",
    },

    item: testCases.map(tc => ({
      name: tc.name || `${tc.method} ${tc.path}`,
      request: {
        method: tc.method.toUpperCase(),
        header: [
          { key: "Content-Type", value: "application/json" }
        ],
        url: {
          raw: `{{baseUrl}}${tc.path}`,
          host: ["{{baseUrl}}"],
          path: tc.path.replace(/^\//, "").split("/"),
        },
        body: tc.requestBody
          ? {
              mode: "raw",
              raw: JSON.stringify(tc.requestBody, null, 2)
            }
          : undefined
      },

      // Postman test scripts
      event: [
        {
          listen: "test",
          script: {
            exec: [
              `pm.test("Status code should be ${tc.expectedStatus}", function () {`,
              `    pm.response.to.have.status(${tc.expectedStatus});`,
              `});`,
              "",
              "// Additional schema or field validation tests may be injected later",
              ""
            ]
          }
        }
      ],

      response: []
    })),

    event: [],
    variable: [
      { key: "baseUrl", value: "http://localhost:3000" }
    ]
  };

  // Ensure folder exists
  const dir = path.dirname(outputPath);
  await fs.mkdir(dir, { recursive: true });

  // Write collection
  await fs.writeFile(outputPath, JSON.stringify(collection, null, 2));

  console.log(`✅ Postman collection generated: ${outputPath}`);
  return outputPath;
}
